services:
  - type: web
    name: todo-app-server
    rootDir: ./server
    plan: free
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PNPM_STORE_PATH
        value: /opt/render/.pnpm-store
    runtime: node
    region: oregon # Change to your preferred region
    branch: main # Change to your deployment branch
